// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLndmLqavMqmhKO2GwdiYUQJrrU2HdTiE',
    appId: '1:689643267252:web:e23a4a862c810f0033a3e1',
    messagingSenderId: '689643267252',
    projectId: 'losthunt-2cf34',
    authDomain: 'losthunt-2cf34.firebaseapp.com',
    storageBucket: 'losthunt-2cf34.firebasestorage.app',
    measurementId: 'G-D18S449SNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRznx5OxmPGnFGusVzrOh8E7ETeNnSSBA',
    appId: '1:689643267252:android:b82450d7eb749d9533a3e1',
    messagingSenderId: '689643267252',
    projectId: 'losthunt-2cf34',
    storageBucket: 'losthunt-2cf34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5eDRjmwyQ5jItyHEqxYwOfzcvCwd5QZ8',
    appId: '1:689643267252:ios:04a97dd63fa3fee933a3e1',
    messagingSenderId: '689643267252',
    projectId: 'losthunt-2cf34',
    storageBucket: 'losthunt-2cf34.firebasestorage.app',
    iosBundleId: 'com.example.treasurehunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLndmLqavMqmhKO2GwdiYUQJrrU2HdTiE',
    appId: '1:689643267252:web:7642e6779c4d105d33a3e1',
    messagingSenderId: '689643267252',
    projectId: 'losthunt-2cf34',
    authDomain: 'losthunt-2cf34.firebaseapp.com',
    storageBucket: 'losthunt-2cf34.firebasestorage.app',
    measurementId: 'G-35QW9LHP8E',
  );
}
